version: "3.3"

services:
  api_go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_go
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - api_go_db

  api_go_db:
    image: postgres:latest
    container_name: api_go_db
    command: [ "postgres", "-c", "max_locks_per_transaction=256" ]
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "api_go_db_postgres:/var/lib/postgresql/data"
    restart: unless-stopped

volumes:
  api_go_db_postgres: